### ISSUE TITLE
Installed .deb but can't find app launch icon anywhere

### ISSUE THREAD

**Issue by gvanto** [milan102/ForeverNote#2]
I'm on ubuntu 18.04

There's no ./forevernote or ./Forevernote application runnable (but installer said it installed OK)

Help appreciated
gvanto

**Comment by milanify** [comment]
If the .deb installed correctly, it should be located in your /opt folder, so /opt/ForeverNote

That is where the .desktop file will be located, which you can click or make a shortcut to launch the file from anywhere you want. Or just launch it from the command line.
